max-tier: 100

tier-up-notification:
  sound:
    enabled: true
    type: 'level_up'
    volume: 1
    pitch: 2
  firework:
    enabled: true

# Tier configuration
1:
  points-required: 0
  rewards:
    message:
      - '&a&lPass+&2: &7Congratulations you are now tier &e1&7.'
      - '&7&o((Tier &e1 &7&orewards have been given to you.))'
    coal:
      commands:
        - 'eco give {player} 25000'
    gold:
      commands:
        - 'say {player} has received premium rewards.'
#
2:
  points-required: 10
  rewards:
    message:
      - '&a&lPass+&2: &7Congratulations you are now tier &e2&7.'
      - '&7&o((Tier &e1 &7&orewards have been given to you.))'
    coal:
      commands:
        - 'eco give {player} 25000'
    gold:
      commands:
        - 'say {player} has received premium rewards.'