max-tier: 100

gui-pages: 1

adaptable-glass:
  active: 15
  reward-pending: yellow
  complete: green

status:


tier-up-notification:
  sound:
    enabled: true
    type: 'level_up'
    volume: 1
    pitch: 2
  firework:
    enabled: true

# Tier configuration
1:
  points-required: 100
  rewards:
    message:
      - '&d&lBattlePass&5: &7Congratulations you are now tier &f1&7.'
      - '&7&o((Tier &f1 &7&orewards have been given to you.))'
    coal:
      commands:
        - 'eco give {player} 25000'
    gold:
      commands:
        - 'say {player} has received premium rewards.'
#
2:
  points-required: 200
  rewards:
    message:
      - '&d&lBattlePass&5: &7Congratulations you are now tier &f2&7.'
      - '&7&o((Tier &f1 &7&orewards have been given to you.))'
    coal:
      commands:
        - 'eco give {player} 25000'
    gold:
      commands:
        - 'say {player} has received premium rewards.'